#line 1 "zl_lexer.cpp"

#line 3 "zl_lexer.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* An opaque pointer. */
#ifndef YY_TYPEDEF_YY_SCANNER_T
#define YY_TYPEDEF_YY_SCANNER_T
typedef void* yyscan_t;
#endif

/* For convenience, these vars (plus the bison vars far below)
   are macros in the reentrant scanner. */
#define yyin yyg->yyin_r
#define yyout yyg->yyout_r
#define yyextra yyg->yyextra_r
#define yyleng yyg->yyleng_r
#define yytext yyg->yytext_r
#define yylineno (YY_CURRENT_BUFFER_LVALUE->yy_bs_lineno)
#define yycolumn (YY_CURRENT_BUFFER_LVALUE->yy_bs_column)
#define yy_flex_debug yyg->yy_flex_debug_r

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yyg->yy_start = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yyg->yy_start - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin , yyscanner )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = yyg->yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yyg->yy_c_buf_p = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, yyg->yytext_ptr , yyscanner )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( yyg->yy_buffer_stack \
                          ? yyg->yy_buffer_stack[yyg->yy_buffer_stack_top] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE yyg->yy_buffer_stack[yyg->yy_buffer_stack_top]

void yyrestart ( FILE *input_file , yyscan_t yyscanner );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer , yyscan_t yyscanner );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size , yyscan_t yyscanner );
void yy_delete_buffer ( YY_BUFFER_STATE b , yyscan_t yyscanner );
void yy_flush_buffer ( YY_BUFFER_STATE b , yyscan_t yyscanner );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer , yyscan_t yyscanner );
void yypop_buffer_state ( yyscan_t yyscanner );

static void yyensure_buffer_stack ( yyscan_t yyscanner );
static void yy_load_buffer_state ( yyscan_t yyscanner );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file , yyscan_t yyscanner );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER , yyscanner)

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size , yyscan_t yyscanner );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str , yyscan_t yyscanner );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len , yyscan_t yyscanner );

void *yyalloc ( yy_size_t , yyscan_t yyscanner );
void *yyrealloc ( void *, yy_size_t , yyscan_t yyscanner );
void yyfree ( void * , yyscan_t yyscanner );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap(yyscanner) (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

typedef int yy_state_type;

#define yytext_ptr yytext_r

static yy_state_type yy_get_previous_state ( yyscan_t yyscanner );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  , yyscan_t yyscanner);
static int yy_get_next_buffer ( yyscan_t yyscanner );
static void yynoreturn yy_fatal_error ( const char* msg , yyscan_t yyscanner );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yyg->yytext_ptr = yy_bp; \
	yyg->yytext_ptr -= yyg->yy_more_len; \
	yyleng = (int) (yy_cp - yyg->yytext_ptr); \
	yyg->yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yyg->yy_c_buf_p = yy_cp;
#define YY_NUM_RULES 113
#define YY_END_OF_BUFFER 114
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[415] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,  114,  107,  103,  103,   96,  107,   96,   96,
       96,  107,   96,   96,   96,   96,   96,   99,   99,   96,
       96,   96,  102,  102,  102,  102,   96,  102,  102,  102,
      102,  102,  102,  102,  102,  102,  102,  102,  102,  102,
      102,  102,  102,   96,  113,  104,  106,   96,   96,  102,
      102,  102,  102,  102,  102,  102,  102,  102,  102,  102,
      102,  102,  102,  102,   37,  110,  111,  103,   56,    0,
       97,    0,   88,   57,   89,    0,   98,    0,   86,   62,

       84,   63,   85,   59,    0,  101,  109,    0,   87,  101,
       99,    0,    0,   61,   83,   55,   82,   60,  102,  102,
      102,  102,   91,  102,  102,  102,  102,  102,  102,  102,
       40,  102,  102,  102,  102,  102,  102,  102,  102,   38,
      102,  102,  102,  102,  102,  102,  102,  102,  102,  102,
      102,  102,  102,  102,  102,   90,   58,  104,    0,  102,
      102,  102,  102,  102,  102,  102,  102,  102,  102,  102,
      102,  102,  102,  102,  102,  102,   34,  102,  102,  102,
       28,  102,  102,  102,  102,  102,  102,  102,  110,  112,
       97,   98,    0,    0,   80,    0,    0,    0,  108,  101,

        0,  101,  100,   92,   93,  102,  102,  102,  102,  102,
      102,  102,  102,  102,  102,  102,  102,  102,  102,  102,
      102,  102,  102,  102,  102,   45,  102,  102,  102,  102,
       69,  102,   49,  102,  102,  102,  102,  102,  102,  102,
      102,  102,  102,  102,  102,   18,   29,  102,  102,   25,
       22,    3,    9,    7,    5,    4,   11,    6,  102,    1,
        8,   10,    2,   24,   33,   35,   23,   19,   21,   32,
       14,  102,  102,   26,   27,   20,  102,   30,    0,    0,
      105,  102,   94,   95,  102,  102,  102,  102,  102,  102,
      102,  102,   44,   67,  102,  102,  102,   39,  102,  102,

      102,   65,  102,   48,  102,   70,  102,  102,  102,  102,
      102,  102,  102,  102,  102,   76,  102,   16,  102,  102,
       13,  102,   17,    0,  102,  102,  102,  102,  102,  102,
        0,   36,   46,  102,  102,  102,  102,   74,  102,  102,
      102,   71,  102,  102,  102,  102,  102,  102,  102,   41,
      102,  102,   15,  102,  102,  102,  102,  102,  102,  102,
      102,   75,   66,  102,   64,   54,   72,   51,   68,   81,
       42,   52,  102,  102,   12,  102,  102,  102,  102,  102,
      102,   43,  102,  102,  102,  102,   78,   79,  102,  102,
       47,   53,   73,  102,  102,  102,  102,  102,  102,  102,

      102,  102,  102,   77,  102,  102,  102,  102,  102,   31,
      102,  102,   50,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    1,    7,    8,    9,   10,    7,
        7,   11,   12,    7,   13,   14,   15,   16,   17,   17,
       17,   17,   17,   17,   17,   17,   18,    7,    7,   19,
       20,   21,    7,    7,   22,   23,   24,   25,   26,   27,
       28,   28,   29,   28,   28,   30,   31,   32,   33,   34,
       28,   35,   36,   37,   38,   28,   28,   28,   28,   28,
        7,   39,    7,   40,   41,    1,   42,   43,   44,   45,

       46,   47,   48,   49,   50,   51,   52,   53,   54,   55,
       56,   57,   28,   58,   59,   60,   61,   62,   63,   64,
       65,   66,   67,   68,   69,    7,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[70] =
    {   0,
        1,    1,    2,    2,    1,    1,    1,    1,    1,    1,
        3,    1,    1,    1,    1,    4,    4,    4,    1,    1,
        1,    4,    4,    4,    4,    4,    4,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    1,    1,
        5,    4,    4,    4,    4,    4,    4,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    1,    1,    1
    } ;

static const flex_int16_t yy_base[424] =
    {   0,
        0,    0,    0,    0,   69,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,  584,  583,
        0,    0,  593,  596,  137,  140,  572,  139,  596,  571,
      137,  137,  570,  136,  138,  136,  149,  149,  154,  142,
      569,  153,    0,  566,  549,  551,  565,  140,  526,  135,
      133,  130,  143,  527,  143,  526,  131,  535,  156,  128,
      525,  523,  529,  135,  596,  205,  596,  194,  203,  536,
      170,  534,  174,  184,  520,  167,  174,  518,  515,  176,
      528,  187,  525,  514,  596,    0,  554,  236,  596,  202,
      596,  217,  596,  596,  596,  558,  596,  251,  596,  596,

      596,  596,  596,  596,  553,  228,  248,  563,  596,  253,
      259,  270,    0,  545,  596,  596,  596,  544,    0,  533,
      532,  523,  596,  277,  501,  513,  499,  515,  501,  508,
      493,  494,  492,  498,  494,  491,  492,  492,  486,    0,
      488,  484,  488,  485,  488,  480,  483,  194,  480,  487,
      475,  478,  475,  483,  482,  596,  596,  245,  293,  241,
      486,  485,  476,  480,  483,  464,  461,  227,  460,  138,
      470,  465,  267,  477,  463,  453,    0,  218,  465,  460,
        0,  459,  456,  472,  197,  470,  453,  453,    0,  596,
      283,  500,  309,    0,  596,  324,  494,  505,  596,  313,

      316,  324,    0,  596,  596,  471,  476,  479,  471,  481,
      473,  456,  455,  439,  444,  455,  450,  437,  434,  451,
      449,  445,  444,  430,  446,    0,  433,  442,  429,  428,
        0,  435,    0,  429,  420,  422,  424,  432,  203,  417,
      430,  429,  424,  428,  419,    0,    0,  418,  429,    0,
        0,    0,    0,    0,    0,    0,    0,    0,  427,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,  419,  414,    0,    0,    0,  406,    0,  327,  455,
      596,  438,    0,    0,  432,  425,  430,  417,  413,  413,
      343,  405,    0,    0,  406,  394,  401,    0,  395,  406,

      391,    0,  390,    0,  391,    0,  390,  387,  400,  382,
      375,  381,  368,  355,  361,    0,  362,    0,  350,  358,
        0,  352,    0,  394,  369,  376,  375,  352,  355,  354,
      346,  596,    0,  342,  343,  349,  339,    0,  343,  332,
      336,    0,  345,  342,  340,  327,  337,  338,  329,    0,
      325,  323,    0,  352,  339,  338,  337,  324,  334,  314,
      314,    0,    0,  317,    0,    0,    0,    0,    0,    0,
        0,    0,  326,  321,    0,  340,  328,  327,  310,  313,
      319,    0,  309,  318,  307,  335,    0,    0,  302,  305,
        0,    0,    0,  297,  321,  305,  313,  312,  297,  293,

      282,  260,  270,    0,  269,  260,  245,  241,  249,    0,
      244,  222,    0,  596,  413,  418,  423,  428,  430,  435,
      440,  254,  145
    } ;

static const flex_int16_t yy_def[424] =
    {   0,
      414,    1,  415,  415,  414,    5,  415,  415,  415,  415,
      415,  415,  415,  415,  415,  415,  415,  415,  416,  416,
      415,  415,  414,  414,  414,  414,  414,  417,  414,  414,
      414,  418,  414,  414,  414,  414,  414,  414,  414,  414,
      414,  414,  419,  419,  419,  419,  414,  419,  419,  419,
      419,  419,  419,  419,  419,  419,  419,  419,  419,  419,
      419,  419,  419,  414,  414,  414,  414,  414,  414,  419,
      419,  419,  419,  419,  419,  419,  419,  419,  419,  419,
      419,  419,  419,  419,  414,  420,  414,  414,  414,  417,
      414,  417,  414,  414,  414,  414,  414,  414,  414,  414,

      414,  414,  414,  414,  414,  414,  414,  421,  414,  414,
      414,  414,  422,  414,  414,  414,  414,  414,  419,  419,
      419,  419,  414,  419,  419,  419,  419,  419,  419,  419,
      419,  419,  419,  419,  419,  419,  419,  419,  419,  419,
      419,  419,  419,  419,  419,  419,  419,  419,  419,  419,
      419,  419,  419,  419,  419,  414,  414,  414,  414,  419,
      419,  419,  419,  419,  419,  419,  419,  419,  419,  419,
      419,  419,  419,  419,  419,  419,  419,  419,  419,  419,
      419,  419,  419,  419,  419,  419,  419,  419,  420,  414,
      417,  414,  414,  423,  414,  414,  414,  421,  414,  414,

      414,  414,  422,  414,  414,  419,  419,  419,  419,  419,
      419,  419,  419,  419,  419,  419,  419,  419,  419,  419,
      419,  419,  419,  419,  419,  419,  419,  419,  419,  419,
      419,  419,  419,  419,  419,  419,  419,  419,  419,  419,
      419,  419,  419,  419,  419,  419,  419,  419,  419,  419,
      419,  419,  419,  419,  419,  419,  419,  419,  419,  419,
      419,  419,  419,  419,  419,  419,  419,  419,  419,  419,
      419,  419,  419,  419,  419,  419,  419,  419,  414,  423,
      414,  419,  419,  419,  419,  419,  419,  419,  419,  419,
      419,  419,  419,  419,  419,  419,  419,  419,  419,  419,

      419,  419,  419,  419,  419,  419,  419,  419,  419,  419,
      419,  419,  419,  419,  419,  419,  419,  419,  419,  419,
      419,  419,  419,  414,  419,  419,  419,  419,  419,  419,
      414,  414,  419,  419,  419,  419,  419,  419,  419,  419,
      419,  419,  419,  419,  419,  419,  419,  419,  419,  419,
      419,  419,  419,  419,  419,  419,  419,  419,  419,  419,
      419,  419,  419,  419,  419,  419,  419,  419,  419,  419,
      419,  419,  419,  419,  419,  419,  419,  419,  419,  419,
      419,  419,  419,  419,  419,  419,  419,  419,  419,  419,
      419,  419,  419,  419,  419,  419,  419,  419,  419,  419,

      419,  419,  419,  419,  419,  419,  419,  419,  419,  419,
      419,  419,  419,    0,  414,  414,  414,  414,  414,  414,
      414,  414,  414
    } ;

static const flex_int16_t yy_nxt[666] =
    {   0,
       24,   25,   26,   25,   27,   28,   29,   30,   31,   32,
       33,   34,   35,   36,   37,   38,   39,   39,   40,   41,
       42,   43,   43,   43,   43,   43,   44,   43,   43,   43,
       43,   45,   43,   43,   43,   43,   46,   43,   24,   47,
       48,   43,   49,   50,   51,   52,   53,   54,   43,   55,
       43,   43,   56,   43,   57,   43,   43,   58,   59,   60,
       61,   62,   63,   43,   43,   43,   24,   64,   24,   24,
       66,   67,   66,   29,   28,   29,   29,   29,   32,   29,
       29,   29,   68,   69,   38,   39,   39,   29,   29,   29,
       43,   43,   43,   43,   43,   43,   43,   43,   43,   43,

       43,   43,   43,   43,   43,   43,   43,   24,   29,   70,
       71,   43,   72,   73,   74,   43,   43,   43,   75,   76,
       43,   43,   77,   78,   79,   80,   81,   82,   83,   43,
       43,   43,   84,   43,   43,   24,   29,   85,   88,   88,
       88,   88,   88,   88,   91,   94,   97,  100,  280,  105,
      102,  106,  106,  106,  156,  101,   95,  103,  104,  107,
      114,  115,  110,  108,  111,  111,  111,  110,  109,  111,
      111,  111,  117,  118,  112,   98,  127,   92,  130,  112,
      124,  125,  132,  128,  134,  151,  144,  257,  131,  140,
      129,  145,  152,  133,  112,  135,  141,  142,  136,  112,

      137,  258,  157,  138,  147,  148,  158,   91,  158,  106,
      106,  106,  113,  159,  161,  149,  164,  108,  150,  165,
      175,  176,  191,  166,  162,  167,  168,  169,  170,  178,
      171,  182,  177,  172,  179,  185,  183,   88,   88,   88,
       92,  237,  173,  106,  106,  106,  158,  186,  158,  274,
      196,  196,  311,  112,  275,   92,   96,  203,  197,  238,
      192,  196,  267,  312,  209,  210,  193,  193,  200,  200,
      200,  253,  110,  112,  111,  111,  111,  211,  112,  268,
      413,  201,  201,  254,  112,  202,  202,  202,   91,   96,
      255,  412,   96,   96,  411,  196,  196,   96,  112,  410,

      209,  210,  409,  197,  112,   96,  196,  408,   96,  407,
       96,  261,   96,  211,  194,  406,  262,  212,   97,  405,
      213,   92,  404,  263,  279,  279,  196,  196,  200,  200,
      200,  202,  202,  202,  197,  214,   97,  196,  112,  202,
      202,  202,  324,  324,  331,  331,  331,  331,  331,  331,
      403,  402,  401,  400,  399,  398,  397,  283,  112,  396,
      395,  394,  393,  392,  391,  390,  389,  388,  387,  386,
      385,  384,  383,  382,  381,  380,  284,  379,  378,  377,
      376,  375,  374,  373,  372,  371,  370,  369,  368,  367,
      366,  365,  364,  363,  362,  361,  360,  359,  358,  357,

      356,  355,  354,   97,  353,  352,  351,  350,  349,  332,
      348,  347,  332,   65,   65,   65,   65,   65,   86,   86,
       86,   86,   86,   90,  346,   90,   90,   90,   96,  345,
       96,   96,   96,  119,  119,  189,  189,  344,  189,  189,
      198,  198,  198,  198,  198,  343,  342,  341,  340,  339,
      338,  283,  337,  336,  335,  334,  333,  330,  329,  328,
      327,  326,  325,  283,   97,  323,  322,  321,  320,  319,
      318,  317,  316,  315,  314,  284,  313,  310,  309,  308,
      307,  283,  306,  305,  304,  303,  302,  301,  300,  299,
      298,  297,  296,  295,  294,  293,  292,  291,  290,  289,

      288,  287,  286,  285,  284,  283,  282,  199,  281,   97,
      278,  277,  276,  273,  272,  271,  270,  269,  266,  265,
      264,  260,  259,  256,  252,  251,  250,  249,  248,  247,
      246,  245,  244,  243,  242,  241,  240,  239,  236,  235,
      234,  233,  232,  231,  230,  229,  228,  227,  226,  225,
      224,  223,  222,  221,  220,  219,  218,  217,  216,  215,
      208,  207,  206,  205,  204,  199,  195,   97,  190,  188,
      187,  184,  181,  180,  174,  163,  160,  155,  154,  153,
      146,  143,  139,  126,  123,  122,  121,  120,  116,   99,
       93,   89,  414,   87,   87,   23,  414,  414,  414,  414,

      414,  414,  414,  414,  414,  414,  414,  414,  414,  414,
      414,  414,  414,  414,  414,  414,  414,  414,  414,  414,
      414,  414,  414,  414,  414,  414,  414,  414,  414,  414,
      414,  414,  414,  414,  414,  414,  414,  414,  414,  414,
      414,  414,  414,  414,  414,  414,  414,  414,  414,  414,
      414,  414,  414,  414,  414,  414,  414,  414,  414,  414,
      414,  414,  414,  414,  414
    } ;

static const flex_int16_t yy_chk[666] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,

        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,   25,   25,
       25,   26,   26,   26,   28,   31,   32,   34,  423,   36,
       35,   36,   36,   36,   64,   34,   31,   35,   35,   37,
       40,   40,   38,   37,   38,   38,   38,   39,   37,   39,
       39,   39,   42,   42,   38,   32,   50,   28,   51,   39,
       48,   48,   52,   50,   53,   60,   57,  170,   51,   55,
       50,   57,   60,   52,   38,   53,   55,   55,   53,   39,

       53,  170,   64,   53,   59,   59,   66,   90,   66,   68,
       68,   68,   38,   69,   71,   59,   73,   69,   59,   73,
       76,   76,   92,   73,   71,   74,   74,   74,   74,   77,
       74,   80,   76,   74,   77,   82,   80,   88,   88,   88,
       90,  148,   74,  106,  106,  106,  158,   82,  158,  185,
      107,  107,  239,  106,  185,   92,   98,  422,  107,  148,
       98,  107,  178,  239,  160,  160,   98,   98,  110,  110,
      110,  168,  111,  106,  111,  111,  111,  160,  110,  178,
      412,  112,  112,  168,  111,  112,  112,  112,  191,   98,
      168,  411,   98,   98,  409,  159,  159,   98,  110,  408,

      124,  124,  407,  159,  111,   98,  159,  406,   98,  405,
       98,  173,   98,  124,   98,  403,  173,  124,  193,  402,
      124,  191,  401,  173,  193,  193,  196,  196,  200,  200,
      200,  201,  201,  201,  196,  124,  279,  196,  200,  202,
      202,  202,  279,  279,  291,  291,  291,  331,  331,  331,
      400,  399,  398,  397,  396,  395,  394,  390,  200,  389,
      386,  385,  384,  383,  381,  380,  379,  378,  377,  376,
      374,  373,  364,  361,  360,  359,  358,  357,  356,  355,
      354,  352,  351,  349,  348,  347,  346,  345,  344,  343,
      341,  340,  339,  337,  336,  335,  334,  330,  329,  328,

      327,  326,  325,  324,  322,  320,  319,  317,  315,  291,
      314,  313,  331,  415,  415,  415,  415,  415,  416,  416,
      416,  416,  416,  417,  312,  417,  417,  417,  418,  311,
      418,  418,  418,  419,  419,  420,  420,  310,  420,  420,
      421,  421,  421,  421,  421,  309,  308,  307,  305,  303,
      301,  300,  299,  297,  296,  295,  292,  290,  289,  288,
      287,  286,  285,  282,  280,  277,  273,  272,  259,  249,
      248,  245,  244,  243,  242,  241,  240,  238,  237,  236,
      235,  234,  232,  230,  229,  228,  227,  225,  224,  223,
      222,  221,  220,  219,  218,  217,  216,  215,  214,  213,

      212,  211,  210,  209,  208,  207,  206,  198,  197,  192,
      188,  187,  186,  184,  183,  182,  180,  179,  176,  175,
      174,  172,  171,  169,  167,  166,  165,  164,  163,  162,
      161,  155,  154,  153,  152,  151,  150,  149,  147,  146,
      145,  144,  143,  142,  141,  139,  138,  137,  136,  135,
      134,  133,  132,  131,  130,  129,  128,  127,  126,  125,
      122,  121,  120,  118,  114,  108,  105,   96,   87,   84,
       83,   81,   79,   78,   75,   72,   70,   63,   62,   61,
       58,   56,   54,   49,   47,   46,   45,   44,   41,   33,
       30,   27,   23,   20,   19,  414,  414,  414,  414,  414,

      414,  414,  414,  414,  414,  414,  414,  414,  414,  414,
      414,  414,  414,  414,  414,  414,  414,  414,  414,  414,
      414,  414,  414,  414,  414,  414,  414,  414,  414,  414,
      414,  414,  414,  414,  414,  414,  414,  414,  414,  414,
      414,  414,  414,  414,  414,  414,  414,  414,  414,  414,
      414,  414,  414,  414,  414,  414,  414,  414,  414,  414,
      414,  414,  414,  414,  414
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() (yyg->yy_more_flag = 1)
#define YY_MORE_ADJ yyg->yy_more_len
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
#line 2 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"

#include <malloc.h>
//#include "zl_parser.h"
#include "zl_parser.hpp"
#include "zl_compiler.h"

#define YY_EXTRA_TYPE cl_parser_params *
#define YYPP yyget_extra(yyscanner)
#define YY_DECL int yylex(zlval *yylval, yyscan_t yyscanner)

#define YY_INPUT(buf,result,max_size) \
	memcpy(buf, YYPP->source_code + YYPP->sc_offset, ((YYPP->sc_length - YYPP->sc_offset) > ((unsigned long) max_size))?max_size:(YYPP->sc_length - YYPP->sc_offset));\
	result = ((YYPP->sc_length - YYPP->sc_offset)> ((unsigned long) max_size))?max_size:(YYPP->sc_length - YYPP->sc_offset);\
	YYPP->sc_offset += result;

#define YY_NO_UNISTD_H			1

#define TRACK_LINES(s, l)						\
do {											\
	char *p = (s), *boundary = p+(l);			\
												\
	while (p<boundary)							\
	{											\
		if (*p == '\n') {						\
			YYPP->lineno++;						\
		}										\
		p++;									\
	}											\
} while (0)

#define TRACK_LINE(c) \
{ \
	if (c == '\n') \
	{ \
		YYPP->lineno++; \
	} \
}

#line 748 "zl_lexer.cpp"

/* %option noyylineno */
#line 751 "zl_lexer.cpp"

#define INITIAL 0
#define ST_IN_SCRIPTING 1
#define ST_IN_ASM 2
#define ST_DOUBLE_QUOTES 3
#define ST_SINGLE_QUOTE 4
#define ST_BACKQUOTE 5
#define ST_HEREDOC 6
#define ST_LOOKING_FOR_PROPERTY 7
#define ST_LOOKING_FOR_VARNAME 8
#define ST_COMMENT 9
#define ST_ONE_LINE_COMMENT 10

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

/* Holds the entire state of the reentrant scanner. */
struct yyguts_t
    {

    /* User-defined. Not touched by flex. */
    YY_EXTRA_TYPE yyextra_r;

    /* The rest are the same as the globals declared in the non-reentrant scanner. */
    FILE *yyin_r, *yyout_r;
    size_t yy_buffer_stack_top; /**< index of top of stack. */
    size_t yy_buffer_stack_max; /**< capacity of stack. */
    YY_BUFFER_STATE * yy_buffer_stack; /**< Stack as an array. */
    char yy_hold_char;
    int yy_n_chars;
    int yyleng_r;
    char *yy_c_buf_p;
    int yy_init;
    int yy_start;
    int yy_did_buffer_switch_on_eof;
    int yy_start_stack_ptr;
    int yy_start_stack_depth;
    int *yy_start_stack;
    yy_state_type yy_last_accepting_state;
    char* yy_last_accepting_cpos;

    int yylineno_r;
    int yy_flex_debug_r;

    char *yytext_r;
    int yy_more_flag;
    int yy_more_len;

    }; /* end struct yyguts_t */

static int yy_init_globals ( yyscan_t yyscanner );

int yylex_init (yyscan_t* scanner);

int yylex_init_extra ( YY_EXTRA_TYPE user_defined, yyscan_t* scanner);

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( yyscan_t yyscanner );

int yyget_debug ( yyscan_t yyscanner );

void yyset_debug ( int debug_flag , yyscan_t yyscanner );

YY_EXTRA_TYPE yyget_extra ( yyscan_t yyscanner );

void yyset_extra ( YY_EXTRA_TYPE user_defined , yyscan_t yyscanner );

FILE *yyget_in ( yyscan_t yyscanner );

void yyset_in  ( FILE * _in_str , yyscan_t yyscanner );

FILE *yyget_out ( yyscan_t yyscanner );

void yyset_out  ( FILE * _out_str , yyscan_t yyscanner );

			int yyget_leng ( yyscan_t yyscanner );

char *yyget_text ( yyscan_t yyscanner );

int yyget_lineno ( yyscan_t yyscanner );

void yyset_lineno ( int _line_number , yyscan_t yyscanner );

int yyget_column  ( yyscan_t yyscanner );

void yyset_column ( int _column_no , yyscan_t yyscanner );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( yyscan_t yyscanner );
#else
extern int yywrap ( yyscan_t yyscanner );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int , yyscan_t yyscanner);
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * , yyscan_t yyscanner);
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( yyscan_t yyscanner );
#else
static int input ( yyscan_t yyscanner );
#endif

#endif

    static void yy_push_state ( int _new_state , yyscan_t yyscanner);
    
    static void yy_pop_state ( yyscan_t yyscanner );
    
    static int yy_top_state ( yyscan_t yyscanner );
    
/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg , yyscanner)
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (yyscan_t yyscanner);

#define YY_DECL int yylex (yyscan_t yyscanner)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( !yyg->yy_init )
		{
		yyg->yy_init = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yyg->yy_start )
			yyg->yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack (yyscanner);
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner);
		}

		yy_load_buffer_state( yyscanner );
		}

	{
#line 73 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"


#line 1028 "zl_lexer.cpp"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yyg->yy_more_len = 0;
		if ( yyg->yy_more_flag )
			{
			yyg->yy_more_len = (int) (yyg->yy_c_buf_p - yyg->yytext_ptr);
			yyg->yy_more_flag = 0;
			}
		yy_cp = yyg->yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yyg->yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yyg->yy_start;
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				yyg->yy_last_accepting_state = yy_current_state;
				yyg->yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 415 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 414 );
		yy_cp = yyg->yy_last_accepting_cpos;
		yy_current_state = yyg->yy_last_accepting_state;

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yyg->yy_hold_char;
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 75 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
{
	yylval->value = 0; // register offset at regs table
	yylval->flags = ARG_REG;
	return T_REGISTER;
}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 81 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
{
	yylval->value = 1;
	yylval->flags = ARG_REG;
	return T_REGISTER;
}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 87 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
{
	yylval->value = 2;
	yylval->flags = ARG_REG;
	return T_REGISTER;
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 93 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
{
	yylval->value = 3;
	yylval->flags = ARG_REG;
	return T_REGISTER;
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 99 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
{
	yylval->value = 4;
	yylval->flags = ARG_REG;
	return T_REGISTER;
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 105 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
{
	yylval->value = 5;
	yylval->flags = ARG_REG;
	return T_REGISTER;
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 111 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
{
	yylval->value = 6;
	yylval->flags = ARG_REG;
	return T_REGISTER;
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 117 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
{
	yylval->value = 7;
	yylval->flags = ARG_REG;
	return T_REGISTER;
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 123 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
{
	yylval->value = 8;
	yylval->flags = ARG_REG;
	return T_REGISTER;
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 129 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
{
	yylval->value = 9;
	yylval->flags = ARG_REG;
	return T_REGISTER;
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 135 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
{
	yylval->value = 10;
	yylval->flags = ARG_REG;
	return T_REGISTER;
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 141 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
{
	yylval->value = 11;
	yylval->flags = ARG_REG;
	return T_REGISTER;
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 147 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
{
	yylval->value = INS_PUSH;
	return T_OPERATOR;
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 152 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
{
	yylval->value = INS_POP;
	return T_OPERATOR;
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 157 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
{
	yylval->value = INS_RCALL;
	return T_OPERATOR;
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 162 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
{
	yylval->value = INS_CALL;
	return T_OPERATOR;
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 167 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
{
	yylval->value = INS_TEST;
	return T_OPERATOR;
}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 172 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
{
	yylval->value = INS_ADD;
	return T_OPERATOR;
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 177 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
{
	yylval->value = INS_MOV;
	return T_OPERATOR;
}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 182 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
{
	yylval->value = INS_SUB;
	return T_OPERATOR;
}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 187 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
{
	yylval->value = INS_MUL;
	return T_OPERATOR;
}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 192 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
{
	yylval->value = INS_DIV;
	return T_OPERATOR;
}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 197 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
{
	yylval->value = INS_MOD;
	return T_OPERATOR;
}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 202 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
{
	yylval->value = INS_INC;
	return T_OPERATOR;
}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 207 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
{
	yylval->value = INS_DEC;
	return T_OPERATOR;
}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 212 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
{
	yylval->value = INS_SHL;
	return T_OPERATOR;
}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 217 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
{
	yylval->value = INS_SHR;
	return T_OPERATOR;
}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 222 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
{
	yylval->value = INS_OR;
	return T_OPERATOR;
}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 227 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
{
	yylval->value = INS_AND;
	return T_OPERATOR;
}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 232 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
{
	yylval->value = INS_XOR;
	return T_OPERATOR;
}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 237 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
{
	yylval->value = INS_DBG_PRINT;
	return T_OPERATOR;
}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 242 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
{
	yylval->value = INS_NOP;
	return T_OPERATOR;
}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 247 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
{
	yylval->value = OP_JMP;
	return T_GOTO;
}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 252 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
{
	yylval->value = OP_JZ;
	return T_GOTO;
}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 257 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
{
	yylval->value = OP_JNZ;
	return T_GOTO;
}
	YY_BREAK
case 36:
/* rule 36 can match eol */
YY_RULE_SETUP
#line 262 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
{
	TRACK_LINES(yytext, yyleng);
	BEGIN(ST_IN_ASM);
	return T_ASM;
}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 268 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
{
	BEGIN(INITIAL);
	return yytext[0];
}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 273 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
{
	return T_IF;
}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 277 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
{
	return T_ELSE;
}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 281 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
{
	return T_DO;
}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 285 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
{
	return T_WHILE;
}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 289 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
{
	return T_SWITCH;
}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 293 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
{
	return T_DEFAULT;
}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 297 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
{
	return T_CASE;
}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 301 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
{
	return T_FOR;
}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 305 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
{
	return T_BREAK;
}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 309 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
{
	return T_CONTINUE;
}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 313 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
{
	yylval->value = OP_JMP;
	return T_GOTO;
}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 318 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
{
	return T_NOP;
}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 322 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
{
	return T_DBG_PRINT_REGS;
}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 326 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
{
	return T_SIZEOF;
}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 330 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
{
	return T_TYPEOF;
}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 334 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
{
	return T_FUNCTION;
}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 338 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
{
	return T_RETURN;
}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 342 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
{
	return T_EQ;
}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 346 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
{
	return T_NE;
}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 350 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
{
	return T_AND;
}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 354 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
{
	return T_OR;
}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 358 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
{
	return T_PTR_OP;
}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 362 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
{
	return T_SHR;
}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 366 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
{
	return T_SHL;
}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 370 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
{
	return T_INC;
}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 374 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
{
	return T_DEC;
}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 378 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
{
	return T_IMPORT;
}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 382 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
{
	return T_FROM;
}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 386 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
{
	return T_EXTERN;
}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 390 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
{
	return T_CHAR;
}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 394 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
{
	return T_STRING;
}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 398 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
{
	return T_INT;
}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 402 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
{
	return T_LONG;
}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 406 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
{
	return T_SHORT;
}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 410 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
{
	return T_SIGNED;
}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 414 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
{
	return T_UNSIGNED;
}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 418 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
{
	return T_FLOAT;
}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 422 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
{
	return T_DOUBLE;
}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 426 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
{
	return T_VOID;
}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 430 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
{
	//char *text;
	//unsigned long len;

	yylval->string = cl_strdup("zlc v0.01 compiled at " __DATE__ " " __TIME__ " (c)oded by dEmon");
	yylval->size = strlen(yylval->string)+1;
	//yylval->value = (unsigned long) cl_section_data_push(&YYPP->data_table, ZLF_SECT_CONST, (char *) text, strlen(text)+1);
	//free_str(text);
	yylval->flags = ZLF_UNSIGNED | ZLF_CHAR;
	yylval->flags += 0x01000000;

	return T_CONSTANT_STRING;
}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 444 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
{
	//char *text;
	//unsigned long len;
	
	yylval->string = cl_strdate();
	yylval->size = strlen(yylval->string)+1;
	//yylval->value = (unsigned long) cl_section_data_push(&YYPP->data_table, ZLF_SECT_CONST, (char *) text, strlen(text)+1);
	//free_str(text);
	yylval->flags = ZLF_UNSIGNED | ZLF_CHAR;
	yylval->flags += 0x01000000;

	return T_CONSTANT_STRING;
}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 458 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
{
	//char *text;
	//unsigned long len;
	
	yylval->string = cl_strtime();
	yylval->size = strlen(yylval->string)+1;
	//yylval->value = (unsigned long) cl_section_data_push(&YYPP->data_table, ZLF_SECT_CONST, (char *) text, strlen(text)+1);
	//free_str(text);
	yylval->flags = ZLF_UNSIGNED | ZLF_CHAR;
	yylval->flags += 0x01000000;

	return T_CONSTANT_STRING;
}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 472 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
{
	return T_ELLIPSIS;
}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 476 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
{
	return T_STRUCT;
}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 480 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
{
	return T_GE;
}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 484 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
{
	return T_LE;
}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 488 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
{
	return T_ADD_ASSIGN;
}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 492 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
{
	return T_SUB_ASSIGN;
}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 496 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
{
	return T_MUL_ASSIGN;
}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 500 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
{
	return T_DIV_ASSIGN;
}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 504 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
{
	return T_MOD_ASSIGN;
}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 508 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
{
	return T_AND_ASSIGN;
}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 512 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
{
	return T_OR_ASSIGN;
}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 516 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
{
	return T_XOR_ASSIGN;
}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 520 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
{
	return T_SHL_ASSIGN;
}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 524 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
{
	return T_SHR_ASSIGN;
}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 528 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
{
	yylval->value = 0;
	yylval->flags = ZLF_SIGNED | ZLF_LONG | ZLF_INT;
	return T_CONSTANT_LONG;
}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 534 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
{
	yylval->value = 1;
	yylval->flags = ZLF_SIGNED | ZLF_LONG | ZLF_INT;
	return T_CONSTANT_LONG;
}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 540 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
{
	return yytext[0];
}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 544 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
{
	char *text;
	//char *unesc;
	//unsigned long len;
	
	text = cl_strndup(yytext+1, yyleng-2);
	yylval->string = alloc_unescapestring(text, &yylval->size);
	yylval->size++;
	//yylval->value = (unsigned long) cl_section_data_push(&YYPP->data_table, ZLF_SECT_CONST, (char *) unesc, len+1);
	//free_str(unesc);
	free_str(text);
	yylval->flags = ZLF_UNSIGNED | ZLF_CHAR | ZLF_ARRAY;
	yylval->flags += 0x01000000;
	return T_CONSTANT_STRING;
}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 560 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
{
	char *text, *unesc;
	unsigned long len;
	text = cl_strndup(yytext+1, yyleng-2);
	unesc = alloc_unescapestring(text, &len);
	yylval->value = *unesc;
	free_str(unesc);
	free_str(text);
	yylval->flags = ZLF_SIGNED | ZLF_CHAR;
	return T_CONSTANT_LONG;
}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 572 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
{
    // limits: 
	// 2 bytes:                 –128 ... 127                  255
	// 2 bytes:               –32768 ... 32767                65 535 
    // 4 bytes:          –2147483648 ... 2147483647           4 294 967 295
	// 8 bytes: -9223372036854775808 ... 9223372036854775807  18 446 744 073 709 551 615
	
	yylval->uvalue = cl_strtoul(yytext, yyleng);

	if(yylval->uvalue > 2147483647)
	{
		yylval->flags = ZLF_UNSIGNED | ZLF_LONG | ZLF_INT;
	}
	else
	{
		yylval->flags = ZLF_SIGNED | ZLF_LONG | ZLF_INT;
	}
	return T_CONSTANT_LONG;
}
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 592 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
{
	yylval->uvalue = cl_hextoul(yytext, yyleng);

	if(yylval->uvalue > 2147483647)
	{
		yylval->flags = ZLF_UNSIGNED | ZLF_LONG | ZLF_INT;
	}
	else
	{
		yylval->flags = ZLF_SIGNED | ZLF_LONG | ZLF_INT;
	}
	return T_CONSTANT_LONG;
}
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 606 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
{
	yylval->dvalue = cl_strtod(yytext, yyleng);
	yylval->flags = ZLF_DOUBLE;
	return T_CONSTANT_DOUBLE;
}
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 612 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
{
	yylval->string = cl_strndup(yytext, yyleng);
	return T_LABEL;
}
	YY_BREAK
case 103:
/* rule 103 can match eol */
YY_RULE_SETUP
#line 617 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
{
	TRACK_LINES(yytext, yyleng);
	//return T_WHITESPACE;
}
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 622 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
{
	//return T_WHITESPACE;
}
	YY_BREAK
case 105:
/* rule 105 can match eol */
YY_RULE_SETUP
#line 626 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
{
	TRACK_LINES(yytext, yyleng);
	//return T_WHITESPACE;
}
	YY_BREAK
case 106:
/* rule 106 can match eol */
YY_RULE_SETUP
#line 631 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
{
	YYPP->lineno++;
	return yytext[0];
}
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 636 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
{
	TRACK_LINE(yytext[0]);
	return yytext[0];
}
	YY_BREAK
case 108:
*yy_cp = yyg->yy_hold_char; /* undo effects of setting up yytext */
yyg->yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 641 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
{
	//return T_COMMENT;
}
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 645 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
{
	BEGIN(ST_COMMENT);
	yymore();
}
	YY_BREAK
case 110:
/* rule 110 can match eol */
YY_RULE_SETUP
#line 650 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
{
	yymore();
}
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 654 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
{
	yymore();
}
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 658 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
{
	TRACK_LINES(yytext, yyleng);
	BEGIN(INITIAL);
	//return T_COMMENT;
}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(ST_IN_SCRIPTING):
case YY_STATE_EOF(ST_IN_ASM):
case YY_STATE_EOF(ST_DOUBLE_QUOTES):
case YY_STATE_EOF(ST_SINGLE_QUOTE):
case YY_STATE_EOF(ST_BACKQUOTE):
case YY_STATE_EOF(ST_HEREDOC):
case YY_STATE_EOF(ST_LOOKING_FOR_PROPERTY):
case YY_STATE_EOF(ST_LOOKING_FOR_VARNAME):
case YY_STATE_EOF(ST_COMMENT):
case YY_STATE_EOF(ST_ONE_LINE_COMMENT):
#line 664 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
{
	yyterminate();
}
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 668 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"
ECHO;
	YY_BREAK
#line 2041 "zl_lexer.cpp"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yyg->yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yyg->yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yyg->yy_c_buf_p <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yyg->yy_c_buf_p = yyg->yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state( yyscanner );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state , yyscanner);

			yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yyg->yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yyg->yy_last_accepting_cpos;
				yy_current_state = yyg->yy_last_accepting_state;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer( yyscanner ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yyg->yy_did_buffer_switch_on_eof = 0;

				if ( yywrap( yyscanner ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yyg->yy_c_buf_p = yyg->yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yyg->yy_c_buf_p =
					yyg->yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yyg->yy_c_buf_p =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars];

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = yyg->yytext_ptr;
	int number_to_move, i;
	int ret_val;

	if ( yyg->yy_c_buf_p > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yyg->yy_c_buf_p - yyg->yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yyg->yy_c_buf_p - yyg->yytext_ptr - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) (yyg->yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2) , yyscanner );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yyg->yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			yyg->yy_n_chars, num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	if ( yyg->yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  , yyscanner);
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yyg->yy_n_chars + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = yyg->yy_n_chars + number_to_move + (yyg->yy_n_chars >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size , yyscanner );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	yyg->yy_n_chars += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yyg->yytext_ptr = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (yyscan_t yyscanner)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_current_state = yyg->yy_start;

	for ( yy_cp = yyg->yytext_ptr + YY_MORE_ADJ; yy_cp < yyg->yy_c_buf_p; ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yyg->yy_last_accepting_state = yy_current_state;
			yyg->yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 415 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state , yyscan_t yyscanner)
{
	int yy_is_jam;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner; /* This var may be unused depending upon options. */
	char *yy_cp = yyg->yy_c_buf_p;

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yyg->yy_last_accepting_state = yy_current_state;
		yyg->yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 415 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 414);

	(void)yyg;
	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (yyscan_t yyscanner)
#else
    static int input  (yyscan_t yyscanner)
#endif

{
	int c;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	*yyg->yy_c_buf_p = yyg->yy_hold_char;

	if ( *yyg->yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yyg->yy_c_buf_p < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			/* This was really a NUL. */
			*yyg->yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = (int) (yyg->yy_c_buf_p - yyg->yytext_ptr);
			++yyg->yy_c_buf_p;

			switch ( yy_get_next_buffer( yyscanner ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin , yyscanner);

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( yyscanner ) )
						return 0;

					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput(yyscanner);
#else
					return input(yyscanner);
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yyg->yy_c_buf_p = yyg->yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yyg->yy_c_buf_p;	/* cast for 8-bit char's */
	*yyg->yy_c_buf_p = '\0';	/* preserve yytext */
	yyg->yy_hold_char = *++yyg->yy_c_buf_p;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * @param yyscanner The scanner object.
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack (yyscanner);
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner);
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file , yyscanner);
	yy_load_buffer_state( yyscanner );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * @param yyscanner The scanner object.
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack (yyscanner);
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( yyscanner );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yyg->yy_did_buffer_switch_on_eof = 1;
}

static void yy_load_buffer_state  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	yyg->yytext_ptr = yyg->yy_c_buf_p = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	yyg->yy_hold_char = *yyg->yy_c_buf_p;
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * @param yyscanner The scanner object.
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state ) , yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2) , yyscanner );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file , yyscanner);

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * @param yyscanner The scanner object.
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf , yyscanner );

	yyfree( (void *) b , yyscanner );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file , yyscan_t yyscanner)

{
	int oerrno = errno;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_flush_buffer( b , yyscanner);

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * @param yyscanner The scanner object.
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( yyscanner );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  @param yyscanner The scanner object.
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack(yyscanner);

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		yyg->yy_buffer_stack_top++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( yyscanner );
	yyg->yy_did_buffer_switch_on_eof = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  @param yyscanner The scanner object.
 */
void yypop_buffer_state (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER , yyscanner);
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if (yyg->yy_buffer_stack_top > 0)
		--yyg->yy_buffer_stack_top;

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( yyscanner );
		yyg->yy_did_buffer_switch_on_eof = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (yyscan_t yyscanner)
{
	yy_size_t num_to_alloc;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if (!yyg->yy_buffer_stack) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		yyg->yy_buffer_stack = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset(yyg->yy_buffer_stack, 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		yyg->yy_buffer_stack_max = num_to_alloc;
		yyg->yy_buffer_stack_top = 0;
		return;
	}

	if (yyg->yy_buffer_stack_top >= (yyg->yy_buffer_stack_max) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = yyg->yy_buffer_stack_max + grow_size;
		yyg->yy_buffer_stack = (struct yy_buffer_state**)yyrealloc
								(yyg->yy_buffer_stack,
								num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset(yyg->yy_buffer_stack + yyg->yy_buffer_stack_max, 0, grow_size * sizeof(struct yy_buffer_state*));
		yyg->yy_buffer_stack_max = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state ) , yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b , yyscanner );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr , yyscan_t yyscanner)
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) , yyscanner);
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n , yyscanner );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n , yyscanner);
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

    static void yy_push_state (int  _new_state , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if ( yyg->yy_start_stack_ptr >= yyg->yy_start_stack_depth )
		{
		yy_size_t new_size;

		yyg->yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = (yy_size_t) yyg->yy_start_stack_depth * sizeof( int );

		if ( ! yyg->yy_start_stack )
			yyg->yy_start_stack = (int *) yyalloc( new_size , yyscanner );

		else
			yyg->yy_start_stack = (int *) yyrealloc(
					(void *) yyg->yy_start_stack, new_size , yyscanner );

		if ( ! yyg->yy_start_stack )
			YY_FATAL_ERROR( "out of memory expanding start-condition stack" );
		}

	yyg->yy_start_stack[yyg->yy_start_stack_ptr++] = YY_START;

	BEGIN(_new_state);
}

    static void yy_pop_state  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if ( --yyg->yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yyg->yy_start_stack[yyg->yy_start_stack_ptr]);
}

    static int yy_top_state  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	return yyg->yy_start_stack[yyg->yy_start_stack_ptr - 1];
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = yyg->yy_hold_char; \
		yyg->yy_c_buf_p = yytext + yyless_macro_arg; \
		yyg->yy_hold_char = *yyg->yy_c_buf_p; \
		*yyg->yy_c_buf_p = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the user-defined data for this scanner.
 * @param yyscanner The scanner object.
 */
YY_EXTRA_TYPE yyget_extra  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyextra;
}

/** Get the current line number.
 * @param yyscanner The scanner object.
 */
int yyget_lineno  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yylineno;
}

/** Get the current column number.
 * @param yyscanner The scanner object.
 */
int yyget_column  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yycolumn;
}

/** Get the input stream.
 * @param yyscanner The scanner object.
 */
FILE *yyget_in  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyin;
}

/** Get the output stream.
 * @param yyscanner The scanner object.
 */
FILE *yyget_out  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyout;
}

/** Get the length of the current token.
 * @param yyscanner The scanner object.
 */
int yyget_leng  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyleng;
}

/** Get the current token.
 * @param yyscanner The scanner object.
 */

char *yyget_text  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yytext;
}

/** Set the user-defined data. This data is never touched by the scanner.
 * @param user_defined The data to be associated with this scanner.
 * @param yyscanner The scanner object.
 */
void yyset_extra (YY_EXTRA_TYPE  user_defined , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyextra = user_defined ;
}

/** Set the current line number.
 * @param _line_number line number
 * @param yyscanner The scanner object.
 */
void yyset_lineno (int  _line_number , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* lineno is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           YY_FATAL_ERROR( "yyset_lineno called with no buffer" );
    
    yylineno = _line_number;
}

/** Set the current column.
 * @param _column_no column number
 * @param yyscanner The scanner object.
 */
void yyset_column (int  _column_no , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* column is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           YY_FATAL_ERROR( "yyset_column called with no buffer" );
    
    yycolumn = _column_no;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * @param yyscanner The scanner object.
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyin = _in_str ;
}

void yyset_out (FILE *  _out_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyout = _out_str ;
}

int yyget_debug  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yy_flex_debug;
}

void yyset_debug (int  _bdebug , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yy_flex_debug = _bdebug ;
}

/* Accessor methods for yylval and yylloc */

/* User-visible API */

/* yylex_init is special because it creates the scanner itself, so it is
 * the ONLY reentrant function that doesn't take the scanner as the last argument.
 * That's why we explicitly handle the declaration, instead of using our macros.
 */
int yylex_init(yyscan_t* ptr_yy_globals)
{
    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) yyalloc ( sizeof( struct yyguts_t ), NULL );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    return yy_init_globals ( *ptr_yy_globals );
}

/* yylex_init_extra has the same functionality as yylex_init, but follows the
 * convention of taking the scanner as the last argument. Note however, that
 * this is a *pointer* to a scanner, as it will be allocated by this call (and
 * is the reason, too, why this function also must handle its own declaration).
 * The user defined value in the first argument will be available to yyalloc in
 * the yyextra field.
 */
int yylex_init_extra( YY_EXTRA_TYPE yy_user_defined, yyscan_t* ptr_yy_globals )
{
    struct yyguts_t dummy_yyguts;

    yyset_extra (yy_user_defined, &dummy_yyguts);

    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) yyalloc ( sizeof( struct yyguts_t ), &dummy_yyguts );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in
    yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    yyset_extra (yy_user_defined, *ptr_yy_globals);

    return yy_init_globals ( *ptr_yy_globals );
}

static int yy_init_globals (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    yyg->yy_buffer_stack = NULL;
    yyg->yy_buffer_stack_top = 0;
    yyg->yy_buffer_stack_max = 0;
    yyg->yy_c_buf_p = NULL;
    yyg->yy_init = 0;
    yyg->yy_start = 0;

    yyg->yy_start_stack_ptr = 0;
    yyg->yy_start_stack_depth = 0;
    yyg->yy_start_stack =  NULL;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER , yyscanner );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state(yyscanner);
	}

	/* Destroy the stack itself. */
	yyfree(yyg->yy_buffer_stack , yyscanner);
	yyg->yy_buffer_stack = NULL;

    /* Destroy the start condition stack. */
        yyfree( yyg->yy_start_stack , yyscanner );
        yyg->yy_start_stack = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( yyscanner);

    /* Destroy the main struct (reentrant only). */
    yyfree ( yyscanner , yyscanner );
    yyscanner = NULL;
    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;

	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s , yyscan_t yyscanner)
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;

	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 668 "C:\\_garbage\\_git\\zlc\\zl_lexer.l"


